version: '3.8'

services:
  pgvector:
    container_name: pgvector-lgcms-local
    image: pgvector/pgvector:pg17
    ports:
      - 38121:5432
    environment:
      - POSTGRES_DB=lgmcs
      - POSTGRES_USER=lgcms
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d
  redis:
    container_name: redis-lgcms-local
    image: valkey/valkey:alpine3.22
    ports:
      - 38122:6379
  kafka:
    container_name: kafka-lgcms-local
    image: bitnamilegacy/kafka:4.0.0-debian-12-r10
    ports:
      - 9092:9092
      - 38123:9094
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://192.168.0.161:38123
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CLUSTER_ID=lgcms-kafka-cluster-001

  kafdrop:
    container_name: kafdrop-lgcms-local
    image: obsidiandynamics/kafdrop:4.0.1
    ports:
      - 38125:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka-lgcms-local:9092
      - JVM_OPTS=-Xms32M -Xmx256M
      - SERVER_SERVLET_CONTEXTPATH=/
    depends_on:
      - kafka
    restart: unless-stopped

  kafka-ui:
    container_name: kafka-ui-lgcms-local
    image: provectuslabs/kafka-ui:latest
    ports:
      - 38126:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=lgcms-local-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-lgcms-local:9092
      - KAFKA_CLUSTERS_0_READONLY=false
    depends_on:
      - kafka
    restart: unless-stopped
