CREATE USER docker;

CREATE DATABASE auth;
CREATE DATABASE consulting;
CREATE DATABASE core;
CREATE DATABASE guide;
CREATE DATABASE lecture;
CREATE DATABASE lesson;
CREATE DATABASE leveltest;
CREATE DATABASE member;
CREATE DATABASE notification;
CREATE DATABASE payment;
CREATE DATABASE tutor;

GRANT ALL PRIVILEGES ON DATABASE auth TO docker;
GRANT ALL PRIVILEGES ON DATABASE consulting TO docker;
GRANT ALL PRIVILEGES ON DATABASE core TO docker;
GRANT ALL PRIVILEGES ON DATABASE guide TO docker;
GRANT ALL PRIVILEGES ON DATABASE lecture TO docker;
GRANT ALL PRIVILEGES ON DATABASE lesson TO docker;
GRANT ALL PRIVILEGES ON DATABASE leveltest TO docker;
GRANT ALL PRIVILEGES ON DATABASE member TO docker;
GRANT ALL PRIVILEGES ON DATABASE notification TO docker;
GRANT ALL PRIVILEGES ON DATABASE payment TO docker;
GRANT ALL PRIVILEGES ON DATABASE tutor TO docker;
