CREATE DATABASE auth;
CREATE DATABASE consulting;
CREATE DATABASE core;
CREATE DATABASE guide;
CREATE DATABASE lecture;
CREATE DATABASE lesson;
CREATE DATABASE leveltest;
CREATE DATABASE member;
CREATE DATABASE notification;
CREATE DATABASE payment;
CREATE DATABASE tutor;

CREATE EXTENSION vector;
